# Generated by Django 4.1 on 2022-08-30 00:27

import Details.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(max_length=255, validators=[Details.validators.dept_name]),
        ),
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(validators=[Details.validators.date_of_birth]),
        ),
        migrations.AlterField(
            model_name='students',
            name='lastname',
            field=models.CharField(max_length=255, validators=[Details.validators.validate_lastname]),
        ),
    ]
